Fix AttributeError in run_sim.py: use args.sim instead of args.config_file
BUG FIX:
When using --sim flag, the argument is stored as 'args.sim', not 'args.config_file'.
Line 1039 was trying to access args.config_file which doesn't exist.

CHANGE:
- Line 1039: Changed 'args.config_file' to 'args.sim'

This fixes the error:
  AttributeError: 'Namespace' object has no attribute 'config_file'

Files modified:
- microc-2.0/tools/run_sim.py